---
name: Build and Deploy react app to GH pages
on:
    push:
        branches: [ main ]
jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Build
          run: npm install
          env:
            REACT_APP_EMAIL_SERVICE_ID: ${{ secrets.REACT_APP_EMAIL_SERVICE_ID }}
            REACT_APP_TEMPLATE_ID: ${{ secrets.REACT_APP_TEMPLATE_ID }}
            REACT_APP_EMAIL_PUBLIC_KEY: ${{ secrets.REACT_APP_EMAIL_PUBLIC_KEY }}

        
        - name: Deploy
          run: |
            git config --global user.name 'Ofer Lis'
            git config --global user.email 'oferlis1@gmail.com'
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            npm run deploy            

